/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package app

import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class AppSuite extends AnyFunSuite {
  test("someAppMethod is always true") {
    def app = new App()
    assert(app.someAppMethod)
  }
}
